let data, view='overview', activePin='', failedAttempts=0, adminState={overviewNote:'',taskOverrides:{}};
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(v);
const titles={overview:'Overview',plan:'Plan & tasks',readiness:'Launch readiness',growth:'Growth & budget',updates:'Updates',library:'Project library'};
const statusClass=s=>({'BLOCKED':'blocked','IN PROGRESS':'progress','NOT STARTED':'neutral','COMPLETE':'complete','PASS':'pass','FAIL':'fail','WAIT':'warn','ON HOLD':'warn'}[s]||'neutral');
const label=s=>({'IN PROGRESS':'In progress','NOT STARTED':'Not started','COMPLETE':'Complete','BLOCKED':'Blocked','WAIT':'Awaiting evidence','PASS':'Passed','FAIL':'Needs work','ON HOLD':'On hold'}[s]||s);
const tag=s=>`<span class="tag ${statusClass(s)}">${esc(label(s))}</span>`;
const taskStatus=t=>adminState.taskOverrides[t.id]||t.status;
const metric=name=>data.metrics.find(m=>m.label===name)||{value:'UNKNOWN',asOf:'UNKNOWN',source:'Unknown'};
const display=v=>v==='UNKNOWN'?'—':esc(v);
const head=(title,sub,extra='')=>`<div class="page-head"><div><div class="eyebrow">PROJECT PULSE</div><h1>${title}</h1><p>${sub}</p></div>${extra}</div>`;
function stat(title,value,note){return `<article class="stat"><div class="label">${title}</div><div class="number">${value}</div><div class="note">${note}</div></article>`;}
function openDetail(kicker,title,body){$('#detail-kicker').textContent=kicker;$('#detail-body').innerHTML=`<h2>${esc(title)}</h2>${body}`;$('#detail').showModal();}
function doc(path){const d=data.docs.find(x=>x.path===path);if(d)openDetail(d.area,d.title,`<p class="subtle">${esc(d.path)}</p><pre class="document">${esc(d.body)}</pre>`);}
function taskDetail(id){const t=data.tasks.find(x=>x.id===id);if(!t)return;openDetail(t.id,t.title,tag(taskStatus(t))+[['Owner',t.owner],['Original target',t.target],['Dependencies',t.dependencies],['Completion evidence required',t.success],['Current evidence',t.evidence],['Local work file',t.source]].map(([k,v])=>`<div class="record-line"><small>${esc(k)}</small><p>${esc(v)}</p></div>`).join(''));}
function overview(){
 const subscribers=metric('Total active subscribers'), blocked=data.tasks.filter(t=>taskStatus(t)==='BLOCKED');
 const feedback=data.registeredFeedback, passed=data.gates.filter(g=>g.group==='Launch'&&g.status==='PASS').length;
 const activePhase=data.phases.find(p=>p.status!=='COMPLETE');
 const owners=data.owners.filter(o=>['OPEN','BLOCKED'].includes(o.status));
 $('#main').innerHTML=head('A clear view of what’s next.','From first feedback to lasting subscriber growth.',`<span class="tag">${activePhase?'Pre-launch':'Growth'}</span>`)+
 `<section class="stats" aria-label="Key project numbers">${stat('Paying subscribers',`${display(subscribers.value)} <span>/ 5 first goal</span>`,esc(subscribers.asOf))}${stat('Useful feedback',`${feedback===null?'—':feedback} <span>/ 10 creators</span>`,feedback===null?'Not yet measured':'Recorded completions · 3 / 6 / 10 checkpoints')}${stat('Budget remaining',money(data.budget.remaining),`${money(data.budget.spent)} spent of ${money(data.budget.total)}`)}${stat('Launch checks passed',`${passed} <span>/ 10</span>`,'Evidence reviewed before approval')}</section>`+
 `<section class="panel admin-note"><div class="panel-head"><div><div class="eyebrow">ADMIN NOTE</div><h2>Overview note</h2></div><span id="note-status" class="save-status">Saved on this device</span></div><div class="panel-body"><textarea id="admin-note" rows="4" maxlength="3000" placeholder="Add a persistent note for this dashboard…">${esc(adminState.overviewNote)}</textarea><div class="note-actions"><small>Private to this browser unless added to the private repository admin state.</small><button id="save-note" class="primary-btn">Save note</button></div></div></section>`+
 `<div class="main-grid"><div class="stack"><section class="focus"><div class="eyebrow">CURRENT FOCUS · ${esc(activePhase?.id||'GROWTH')}</div><h2>${esc(activePhase?.title||'Grow paying subscribers')}</h2><p>${esc(activePhase?.outcome||'Measure acquisition, activation, conversion and retention.')}</p><div class="focus-bottom"><button data-go="plan">Explore the plan <span aria-hidden="true">↗</span></button><small>${blocked.length} tasks blocked · independent work can continue</small></div></section><section class="panel"><div class="panel-head"><h2>Next best actions</h2><button class="text-btn" data-doc="10_DAILY_OPERATIONS/TODAY.md">Daily brief ↗</button></div><div class="task-list">${data.priorities.slice(0,3).map((p,i)=>`<div class="next-item"><span class="step-num">0${i+1}</span><p>${esc(p)}</p></div>`).join('')}</div></section></div><div class="stack"><section class="panel"><div class="panel-head"><h2>Needs attention</h2><span class="tag warn">${owners.length} dependencies</span></div><div class="panel-body">${owners.slice(0,2).map(o=>`<div class="action-card"><div class="meta"><small class="subtle">${esc(o.id)}</small><span class="tag ${o.status==='BLOCKED'?'blocked':'warn'}">${o.status==='BLOCKED'?'Blocked':'Pending'}</span></div><p>${esc(o.action)}</p></div>`).join('')||'<p class="subtle">No open owner dependencies recorded.</p>'}<button class="text-btn section-gap" data-doc="00_ADMIN/OWNER_ACTIONS.md">View all dependencies ↗</button></div></section><section class="panel"><div class="panel-head"><h2>Feedback journey</h2><small>${feedback===null?'Unknown':feedback+' recorded'}</small></div><div class="panel-body"><p class="subtle">Learn, fix and retest between each wave.</p><div class="feedback-dots" aria-label="${feedback??'Unknown'} of 10 feedback participants">${Array.from({length:10},(_,i)=>`<i class="${feedback!==null&&i<feedback?'done':''}"></i>`).join('')}</div><div class="feedback-markers"><span>3 · first learning</span><span>6 · retest</span><span>10 · validate</span></div></div></section></div></div>`+
 `<section class="panel section-gap"><div class="panel-head"><h2>The path to launch</h2><button class="text-btn" data-go="readiness">Readiness checks ↗</button></div><div class="journey">${data.phases.map(p=>`<button data-phase="${esc(p.id)}" class="${p.status==='BLOCKED'?'blocked':p.status==='IN PROGRESS'?'current':''}" aria-label="${esc(p.title)} details"><div class="track"></div><small>${esc(p.id)}</small><h3>${esc(p.title)}</h3><span class="phase-state">${esc(label(p.status))}</span></button>`).join('')}</div></section>`;
}
function plan(){
 $('#main').innerHTML=head('The work, in order.','Seven delivery phases, followed by ongoing acquisition and retention.')+`<div class="toolbar"><input id="task-search" type="search" placeholder="Search tasks, IDs or dependencies…" aria-label="Search tasks"><select id="task-filter" aria-label="Filter tasks by status"><option value="ALL">All statuses</option>${['BLOCKED','IN PROGRESS','NOT STARTED','COMPLETE'].map(s=>`<option value="${s}">${label(s)}</option>`).join('')}</select></div><div class="status-count" id="task-count"></div><section class="panel table-wrap"><table><thead><tr><th>Task</th><th>Status</th><th>Owner</th><th>Original target</th><th>Admin</th></tr></thead><tbody id="tasks"></tbody></table></section><section class="panel section-gap"><div class="panel-body"><h2>After launch</h2><p class="subtle section-gap">Continue acquisition, content, creator relationships, conversion and retention toward 5 → 10 → 25 → 50 → 100 paying subscribers. Release paid-test funds only with evidence and approval.</p><button class="text-btn section-gap" data-doc="01_STRATEGY/GROWTH_PLAN.md">Read the complete master plan ↗</button></div></section>`;
 const render=()=>{const q=$('#task-search').value.toLowerCase(),s=$('#task-filter').value;const rows=data.tasks.filter(t=>(s==='ALL'||taskStatus(t)===s)&&`${t.id} ${t.title} ${t.dependencies}`.toLowerCase().includes(q));$('#task-count').textContent=`${rows.length} of ${data.tasks.length} tasks · manual changes are saved on this device`;$('#tasks').innerHTML=rows.map(t=>{const status=taskStatus(t);return `<tr><td><span class="task-code">${esc(t.id)}</span><button class="task-title" data-task="${esc(t.id)}">${esc(t.title)}</button></td><td>${tag(status)}</td><td>${esc(t.owner)}</td><td>${esc(t.target)}</td><td><button class="task-toggle ${status==='COMPLETE'?'reopen':''}" data-task-toggle="${esc(t.id)}">${status==='COMPLETE'?'Reopen':'Close task'}</button></td></tr>`;}).join('')||'<tr><td colspan="5" class="empty">No tasks match this search.</td></tr>';};$('#task-search').addEventListener('input',render);$('#task-filter').addEventListener('change',render);render();
}
function readiness(){
 $('#main').innerHTML=head('Evidence before the next step.','Readiness is a reviewed decision. Missing evidence stays visible.')+`<div class="callout">Creator outreach waits for social proof and recruitment readiness. Official launch requires all launch checks plus the final team decision.</div><div class="tabs" role="group" aria-label="Readiness category"><button class="selected" data-gate-group="Launch" aria-pressed="true">Official launch</button><button data-gate-group="Social proof" aria-pressed="false">Social proof</button></div><div id="gate-count" class="status-count"></div><div id="gates" class="gate-list"></div>`;
 showGates('Launch');
}
function showGates(group){const gates=data.gates.filter(g=>g.group===group);document.querySelectorAll('[data-gate-group]').forEach(b=>{b.classList.toggle('selected',b.dataset.gateGroup===group);b.setAttribute('aria-pressed',String(b.dataset.gateGroup===group));});$('#gate-count').textContent=`${gates.filter(g=>g.status==='PASS').length} of ${gates.length} passed · reviewed evidence required`;
 $('#gates').innerHTML=gates.map(g=>`<article class="gate"><div class="gate-copy"><small>${esc(g.id)}</small><h3>${esc(g.title)}</h3></div>${tag(g.status)}</article>`).join('');}
function growth(){const b=data.budget;const names=['Total active subscribers','MRR','Activated users','Successful exports'];$('#main').innerHTML=head('Growth that means something.','Subscribers first. Unknown measurements stay unknown.')+`<section class="stats">${names.map(name=>{const m=metric(name);return stat(name,display(m.value),m.value==='UNKNOWN'?'Not yet verified':esc(m.asOf));}).join('')}</section><section class="panel"><div class="panel-head"><h2>Make the $${b.total} count</h2><small>One total project budget</small></div><div class="panel-body budget-layout"><div class="donut" style="--used:${Math.min(100,b.total?b.spent/b.total*100:0)}%"><div class="donut-inner"><strong>${money(b.remaining)}</strong><small>remaining unspent</small></div></div><div class="allocations"><p class="subtle">Planned allocations · each expense needs approval</p>${b.allocations.filter(a=>a.amount>0).map(a=>`<div class="allocation"><span>${esc(a.label)}</span><strong>${money(a.amount)}</strong></div>`).join('')}<p class="subtle section-gap">${money(b.spent)} spent · ${money(b.committed)} committed · ${money(b.proposed)} in expense proposals</p></div></div></section><section class="panel section-gap"><div class="panel-head"><h2>Measurement register</h2><button class="text-btn" data-doc="03_ANALYTICS/METRICS.md">Read evidence ↗</button></div><div class="table-wrap"><table><thead><tr><th>Metric</th><th>Recorded value</th><th>As of / period</th><th>Source</th></tr></thead><tbody>${data.metrics.map(m=>`<tr><td>${esc(m.label)}</td><td>${display(m.value)}</td><td>${m.asOf==='UNKNOWN'?'Not recorded':esc(m.asOf)}</td><td>${esc(m.source)}</td></tr>`).join('')}</tbody></table></div></section><p class="subtle section-gap">A single snapshot cannot establish a trend. Time-series charts can follow when dated observations exist.</p>`;}
function updates(){ $('#main').innerHTML=head('The project’s memory.','Decisions, completed work and changes to the plan.')+`<div class="toolbar"><input id="update-search" type="search" placeholder="Search updates…" aria-label="Search updates"></div><section class="panel"><div class="panel-body" id="timeline"></div></section>`;const render=()=>{const q=$('#update-search').value.toLowerCase();const items=data.updates.filter(u=>`${u.title} ${u.body}`.toLowerCase().includes(q));$('#timeline').innerHTML=items.map((u)=>`<article class="timeline-entry"><time>${esc(u.date||'Date not recorded')}</time><h3>${esc(u.title.replace(/^\d{4}-\d{2}-\d{2}\s*[—–-]?\s*/,''))||'Project update'}</h3><p>${esc(u.body.replace(/[*`#]/g,'').slice(0,230))}${u.body.length>230?'…':''}</p><button class="text-btn section-gap" data-update="${data.updates.indexOf(u)}">Read full update ↗</button></article>`).join('')||'<p class="empty">No matching updates.</p>';};$('#update-search').addEventListener('input',render);render();}
function library(){ $('#main').innerHTML=head('One place for the whole project.','Strategy, research, delivery, content, outreach and operating rules.')+`<div class="toolbar"><input id="doc-search" type="search" placeholder="Search every project document…" aria-label="Search project documents"><select id="doc-area" aria-label="Filter document area"><option value="ALL">All areas</option>${[...new Set(data.docs.map(d=>d.area))].map(a=>`<option>${esc(a)}</option>`).join('')}</select></div><div id="doc-count" class="status-count"></div><div id="docs" class="doc-grid"></div>`;const render=()=>{const q=$('#doc-search').value.toLowerCase(),a=$('#doc-area').value;const docs=data.docs.filter(d=>(a==='ALL'||d.area===a)&&`${d.title} ${d.body}`.toLowerCase().includes(q));$('#doc-count').textContent=`${docs.length} project documents`;$('#docs').innerHTML=docs.map(d=>`<button class="doc-card" data-doc="${esc(d.path)}"><small>${esc(d.area)}</small><h3>${esc(d.title)}</h3><p>Open project record ↗</p></button>`).join('')||'<p class="empty">No matching documents.</p>';};$('#doc-search').addEventListener('input',render);$('#doc-area').addEventListener('change',render);render();}
function navigate(){if(!data)return;view=location.hash.slice(1)||'overview';if(!titles[view])view='overview';$('#crumb').textContent=titles[view];document.querySelectorAll('[data-view]').forEach(a=>{a.classList.toggle('active',a.dataset.view===view);if(a.dataset.view===view)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});({overview,plan,readiness,growth,updates,library}[view])();window.scrollTo(0,0);}
const bytesFromB64=value=>Uint8Array.from(atob(value),c=>c.charCodeAt(0));
const b64FromBytes=value=>btoa(String.fromCharCode(...new Uint8Array(value)));
const localKey='reactioncreator-admin-state-v1';
async function pinKey(pin,salt,iterations=120000){const material=await crypto.subtle.importKey('raw',new TextEncoder().encode(pin),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
async function loadAdminState(){const base=data.adminState||{overviewNote:'',taskOverrides:{}};adminState={overviewNote:base.overviewNote||'',taskOverrides:{...(base.taskOverrides||{})}};const saved=localStorage.getItem(localKey);if(!saved)return;try{const payload=JSON.parse(saved),key=await pinKey(activePin,bytesFromB64(payload.salt),payload.iterations),clear=await crypto.subtle.decrypt({name:'AES-GCM',iv:bytesFromB64(payload.iv)},key,bytesFromB64(payload.ciphertext)),local=JSON.parse(new TextDecoder().decode(clear));if(typeof local.overviewNote==='string')adminState.overviewNote=local.overviewNote;if(local.taskOverrides&&typeof local.taskOverrides==='object')Object.assign(adminState.taskOverrides,local.taskOverrides);}catch{localStorage.removeItem(localKey);}}
async function saveAdminState(){const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),iterations=120000,key=await pinKey(activePin,salt,iterations),clear=new TextEncoder().encode(JSON.stringify(adminState)),ciphertext=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,clear);localStorage.setItem(localKey,JSON.stringify({iterations,salt:b64FromBytes(salt),iv:b64FromBytes(iv),ciphertext:b64FromBytes(ciphertext)}));}
async function decryptSnapshot(pin){
 const r=await fetch(`encrypted-data.json?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error('Snapshot unavailable');
 const payload=await r.json();const material=await crypto.subtle.importKey('raw',new TextEncoder().encode(pin),'PBKDF2',false,['deriveKey']);
 const key=await crypto.subtle.deriveKey({name:'PBKDF2',salt:bytesFromB64(payload.salt),iterations:payload.iterations,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['decrypt']);
 const clear=await crypto.subtle.decrypt({name:'AES-GCM',iv:bytesFromB64(payload.iv)},key,bytesFromB64(payload.ciphertext));
 return JSON.parse(new TextDecoder().decode(clear));
}
function reveal(){document.querySelectorAll('.app-shell').forEach(el=>el.hidden=false);$('#lock').hidden=true;navigate();$('#footer').innerHTML=`<span>Project records: ${esc(data.projectDate||'date unknown')} · individual metrics carry their own dates</span><span>Snapshot generated ${esc(new Date(data.generatedAt).toLocaleString())}</span>`;}
async function unlock(pin){const help=$('#pin-help'),button=$('#unlock-form button');button.disabled=true;help.className='pin-help';help.textContent='Unlocking…';try{const next=await decryptSnapshot(pin);if(!Array.isArray(next.tasks)||!next.budget)throw new Error('Invalid snapshot');data=next;activePin=pin;await loadAdminState();failedAttempts=0;reveal();}catch{failedAttempts++;help.className='pin-help error';help.textContent='Incorrect PIN. Try again.';$('#pin').value='';$('#pin').focus();if(failedAttempts>=3)await new Promise(resolve=>setTimeout(resolve,Math.min(5000,failedAttempts*750)));}finally{button.disabled=false;}}
async function load(){const b=$('#refresh');b.disabled=true;b.textContent='Refreshing…';try{const next=await decryptSnapshot(activePin);if(!Array.isArray(next.tasks)||!next.budget)throw new Error('Invalid snapshot');data=next;navigate();$('#footer').innerHTML=`<span>Project records: ${esc(data.projectDate||'date unknown')} · individual metrics carry their own dates</span><span>Snapshot generated ${esc(new Date(data.generatedAt).toLocaleString())}</span>`;}catch{$('#main').innerHTML='<div class="panel empty"><h2>Couldn’t load the project snapshot.</h2><p>Reload the page and unlock it again. No metrics have been substituted.</p></div>';}finally{b.disabled=false;b.textContent='↻ Refresh snapshot';}}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.go)location.hash=b.dataset.go;if(b.dataset.doc)doc(b.dataset.doc);if(b.dataset.task)taskDetail(b.dataset.task);if(b.dataset.taskToggle){const task=data.tasks.find(t=>t.id===b.dataset.taskToggle),current=taskStatus(task);adminState.taskOverrides[task.id]=current==='COMPLETE'?(task.status==='COMPLETE'?'IN PROGRESS':task.status):'COMPLETE';await saveAdminState();plan();}if(b.id==='save-note'){adminState.overviewNote=$('#admin-note').value.trim();await saveAdminState();$('#note-status').textContent='Saved just now';}if(b.dataset.gateGroup)showGates(b.dataset.gateGroup);if(b.dataset.phase){const p=data.phases.find(p=>p.id===b.dataset.phase);openDetail(p.id,p.title,tag(p.status)+`<p>${esc(p.outcome)}</p><div class="record-line"><small>Current evidence</small>${esc(p.note)}</div><div class="record-line"><small>Original target</small>${esc(p.target)}</div><p class="subtle">Task dependencies and gate evidence govern advancement.</p>`);}if(b.dataset.update!==undefined){const u=data.updates[Number(b.dataset.update)];openDetail(u.date,u.title,`<pre class="document">${esc(u.body)}</pre>`);}});
$('#unlock-form').addEventListener('submit',e=>{e.preventDefault();const pin=$('#pin').value;if(/^\d{4}$/.test(pin))unlock(pin);});$('#pin').addEventListener('input',e=>{e.target.value=e.target.value.replace(/\D/g,'').slice(0,4);});$('#refresh').addEventListener('click',load);$('#close-detail').addEventListener('click',()=>$('#detail').close());$('#detail').addEventListener('click',e=>{if(e.target===$('#detail')){const r=$('#detail').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('#detail').close();}});window.addEventListener('hashchange',navigate);$('#pin').focus();
