let data, view='overview', activePin='', failedAttempts=0, adminState={overviewNote:'',taskOverrides:{},taskNotes:{},gateOverrides:{},gateNotes:{},project:{},updates:[]}, noteSyncStatus='Loading shared note…';
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(v);
const titles={overview:'Overview',plan:'Plan & tasks',readiness:'Launch readiness',growth:'Growth & budget',updates:'Updates',library:'Project library',admin:'Admin'};
const statusClass=s=>({'BLOCKED':'blocked','IN PROGRESS':'progress','NOT STARTED':'neutral','COMPLETE':'complete','PASS':'pass','FAIL':'fail','WAIT':'warn','ON HOLD':'warn'}[s]||'neutral');
const label=s=>({'IN PROGRESS':'In progress','NOT STARTED':'Not started','COMPLETE':'Complete','BLOCKED':'Blocked','WAIT':'Awaiting evidence','PASS':'Passed','FAIL':'Needs work','ON HOLD':'On hold'}[s]||s);
const tag=s=>`<span class="tag ${statusClass(s)}">${esc(label(s))}</span>`;
const taskStatus=t=>adminState.taskOverrides[t.id]||t.status;
const gateStatus=g=>adminState.gateOverrides[g.id]||g.status;
const activeLifecycle=()=>adminState.project?.stage||'PRE_LAUNCH';
const lifecycleTitle=value=>({PRE_LAUNCH:'Pre-launch',LAUNCH_READY:'Launch ready',LAUNCHED:'Launched',GROWTH:'Growth'}[value]||value.replaceAll('_',' '));
const dependencyIds=t=>t.dependencies==='None'?[]:t.dependencies.split(',').map(id=>`WB:${id.trim().replace(/^WB:/,'')}`);
const taskReady=t=>['IN PROGRESS','NOT STARTED'].includes(taskStatus(t))&&dependencyIds(t).every(id=>{const dependency=data.tasks.find(x=>x.id===id);return dependency&&taskStatus(dependency)==='COMPLETE';});
const nextLifecycleTasks=lifecycle=>data.tasks.filter(t=>t.lifecycle===lifecycle&&taskReady(t)).sort((a,b)=>(taskStatus(a)==='IN PROGRESS'?-1:1)-(taskStatus(b)==='IN PROGRESS'?-1:1)||a.sourceRow-b.sourceRow);
const metric=name=>data.metrics.find(m=>m.label===name)||{value:'UNKNOWN',asOf:'UNKNOWN',source:'Unknown'};
const display=v=>v==='UNKNOWN'?'—':esc(v);
const head=(title,sub,extra='')=>`<div class="page-head"><div><div class="eyebrow">PROJECT PULSE</div><h1>${title}</h1><p>${sub}</p></div>${extra}</div>`;
function stat(title,value,note){return `<article class="stat"><div class="label">${title}</div><div class="number">${value}</div><div class="note">${note}</div></article>`;}
function openDetail(kicker,title,body){$('#detail-kicker').textContent=kicker;$('#detail-body').innerHTML=`<h2>${esc(title)}</h2>${body}`;$('#detail').showModal();}
function doc(path){const d=data.docs.find(x=>x.path===path);if(d)openDetail(d.area,d.title,`<p class="subtle">${esc(d.path)}</p><pre class="document">${esc(d.body)}</pre>`);}
function taskDetail(id){const t=data.tasks.find(x=>x.id===id);if(!t)return;const phase=data.phases.find(p=>p.id===t.phaseId);openDetail(t.id,t.title,tag(taskStatus(t))+[['Project phase',`${t.phaseId} · ${phase?.title||'Unknown phase'}`],['Admin note',adminState.taskNotes?.[t.id]||'—'],['Owner',t.owner],['Original target',t.target],['Dependencies',t.dependencies],['Completion evidence required',t.success],['Current evidence',t.evidence],['Local work file',t.source]].map(([k,v])=>`<div class="record-line"><small>${esc(k)}</small><p>${esc(v)}</p></div>`).join(''));}
function overview(){
 const subscribers=metric('Total active subscribers');
 const feedback=data.registeredFeedback, passed=data.gates.filter(g=>g.group==='Launch'&&gateStatus(g)==='PASS').length;
 const lifecycle=activeLifecycle(),lifecycleTasks=data.tasks.filter(t=>t.lifecycle===lifecycle),readyTasks=nextLifecycleTasks(lifecycle).slice(0,1);
 const owners=data.owners.filter(o=>['OPEN','BLOCKED'].includes(o.status));
 $('#main').innerHTML=head('A clear view of what’s next.',adminState.project?.headline||'From first feedback to lasting subscriber growth.',`<span class="tag">${esc(lifecycleTitle(lifecycle))}</span>`)+
 `<div class="overview-top"><section class="panel admin-note"><div class="panel-head"><div><div class="eyebrow">ADMIN NOTE</div><h2>Overview note</h2></div><span id="note-status" class="save-status">${esc(noteSyncStatus)}</span></div><div class="panel-body"><textarea id="admin-note" rows="5" maxlength="3000" placeholder="Add a note everyone using this dashboard can see…">${esc(adminState.overviewNote)}</textarea><div class="note-actions"><small>Anyone who unlocks this dashboard can edit or clear this shared note.</small><div class="note-buttons"><button id="clear-note" class="text-btn">Clear</button><button id="save-note" class="primary-btn">Save</button></div></div></div></section><section class="panel summary-card" aria-label="Key project numbers"><div class="panel-head"><div><div class="eyebrow">PROJECT SNAPSHOT</div><h2>Key numbers</h2></div><button class="text-btn" data-go="growth">View details ↗</button></div><div class="summary-grid">${stat('Paying subscribers',`${display(subscribers.value)} <span>/ 5</span>`,esc(subscribers.asOf))}${stat('Useful feedback',`${feedback===null?'—':feedback} <span>/ 10</span>`,feedback===null?'Not yet measured':'3 / 6 / 10 checkpoints')}${stat('Budget remaining',money(data.budget.remaining),`${money(data.budget.spent)} spent`)}${stat('Launch checks passed',`${passed} <span>/ 10</span>`,'Evidence reviewed')}</div></section></div>`+
 `<div class="work-lanes">`+
 `<section class="panel work-lane ai-lane"><div class="lane-number">01</div><div class="lane-content"><div class="panel-head"><div><div class="eyebrow">NEXT UNBLOCKED TASK · ${esc(lifecycleTitle(lifecycle).toUpperCase())}</div><h2>Tell Codex to implement this next</h2><p>The next ready task is selected from the current lifecycle. Blocked tasks and tasks with incomplete dependencies are excluded.</p></div><span class="tag pass">${lifecycleTasks.filter(taskReady).length} ready</span></div><div class="task-list">${readyTasks.map(t=>{const phase=data.phases.find(p=>p.id===t.phaseId);return `<div class="next-item"><span class="step-num">${esc(t.id.replace('WB:',''))}</span><p><strong>${esc(t.title)}</strong><br><small>${esc(t.phaseId)} · ${esc(phase?.title||'')}</small></p></div>`;}).join('')||`<p class="empty">No detailed, dependency-ready task is registered for ${esc(lifecycleTitle(lifecycle))}. Review Admin help needed or add the next lifecycle task to the project plan.</p>`}<div class="lane-actions"><button class="text-btn" data-go="plan">View ${esc(lifecycleTitle(lifecycle))} tasks ↗</button></div></div></div></section>`+
 `<section class="panel work-lane admin-lane"><div class="lane-number">02</div><div class="lane-content"><div class="panel-head"><div><div class="eyebrow">ADMIN HELP NEEDED</div><h2>Work AI cannot complete alone</h2><p>Each card states the exact admin action and what it unlocks.</p></div><span class="tag ${owners.some(o=>o.status==='BLOCKED')?'blocked':'warn'}">${owners.length} dependencies</span></div><div class="panel-body owner-grid">${owners.map(o=>`<article class="action-card"><div class="meta"><small class="subtle">${esc(o.id)}</small><span class="tag ${o.status==='BLOCKED'?'blocked':'warn'}">${o.status==='BLOCKED'?'Blocked':'Admin action'}</span></div><div class="action-detail"><small>WHAT YOU NEED TO DO</small><p>${esc(o.action)}</p></div><div class="action-detail"><small>WHY THIS NEEDS ADMIN</small><p>${esc(o.why)}</p></div><div class="action-facts"><span><small>UNLOCKS</small>${esc(o.blocks)}</span><span><small>WHEN</small>${esc(o.trigger)}</span></div></article>`).join('')||'<p class="subtle">No admin dependencies are open. AI work can continue independently.</p>'}<div class="lane-actions"><button class="text-btn" data-doc="00_ADMIN/OWNER_ACTIONS.md">Open owner actions ↗</button></div></div></div></section>`+
 `</div>`;
}
function plan(){
 const feedback=data.registeredFeedback,current=activeLifecycle();
 $('#main').innerHTML=head('The work, in order.',`Showing tasks for the ${lifecycleTitle(current)} lifecycle. Change Lifecycle in Admin to change this view.`,`<span class="tag">${esc(lifecycleTitle(current))}</span>`)+`<section class="panel"><div class="panel-head"><div><div class="eyebrow">PRE-LAUNCH DELIVERY PHASES</div><h2>The path to launch</h2></div><button class="text-btn" data-go="readiness">Readiness checks ↗</button></div><div class="journey">${data.phases.map(p=>`<button data-phase="${esc(p.id)}" class="${p.status==='IN PROGRESS'?'current':p.status==='BLOCKED'?'blocked':''}" aria-label="Open ${esc(p.title)} details"><div class="track"></div><small>${esc(p.id)}</small><h3>${esc(p.title)}</h3><span class="phase-state">${data.tasks.filter(t=>t.phaseId===p.id).length} tasks · ${esc(label(p.status))}</span></button>`).join('')}</div></section><div class="toolbar section-gap"><input id="task-search" type="search" placeholder="Search tasks, IDs or dependencies…" aria-label="Search tasks"><select id="task-filter" aria-label="Filter tasks by status"><option value="ALL">All statuses</option>${['BLOCKED','IN PROGRESS','NOT STARTED','COMPLETE'].map(s=>`<option value="${s}">${label(s)}</option>`).join('')}</select></div><div class="status-count" id="task-count"></div><section class="panel table-wrap"><table><thead><tr><th>Task</th><th>Phase</th><th>Status</th><th>Owner</th><th>Original target</th><th>Admin</th></tr></thead><tbody id="tasks"></tbody></table></section><section class="panel section-gap"><div class="panel-head"><h2>Feedback journey</h2><small>${feedback===null?'Unknown':feedback+' recorded'}</small></div><div class="panel-body"><p class="subtle">Learn, fix and retest between each wave of real creator use.</p><div class="feedback-dots" aria-label="${feedback??'Unknown'} of 10 feedback participants">${Array.from({length:10},(_,i)=>`<i class="${feedback!==null&&i<feedback?'done':''}"></i>`).join('')}</div><div class="feedback-markers"><span>3 · first learning</span><span>6 · retest</span><span>10 · validate</span></div></div></section><section class="panel section-gap"><div class="panel-body"><h2>After launch</h2><p class="subtle section-gap">No detailed Launched or Growth tasks are registered yet. Those lifecycle views remain empty until evidence-backed post-launch work is added.</p><button class="text-btn section-gap" data-doc="01_STRATEGY/GROWTH_PLAN.md">Read the complete master plan ↗</button></div></section>`;
 const render=()=>{const q=$('#task-search').value.toLowerCase(),s=$('#task-filter').value,scope=data.tasks.filter(t=>t.lifecycle===current);const rows=scope.filter(t=>(s==='ALL'||taskStatus(t)===s)&&`${t.id} ${t.title} ${t.dependencies} ${t.phaseId}`.toLowerCase().includes(q));$('#task-count').textContent=`${rows.length} of ${scope.length} ${lifecycleTitle(current)} tasks · ${scope.filter(taskReady).length} currently ready`;$('#tasks').innerHTML=rows.map(t=>{const status=taskStatus(t),phase=data.phases.find(p=>p.id===t.phaseId);return `<tr><td><span class="task-code">${esc(t.id)}</span><button class="task-title" data-task="${esc(t.id)}">${esc(t.title)}</button></td><td><span class="task-code">${esc(t.phaseId)}</span>${esc(phase?.title||'')}</td><td>${tag(status)}</td><td>${esc(t.owner)}</td><td>${esc(t.target)}</td><td><button class="task-toggle ${status==='COMPLETE'?'reopen':''}" data-task-toggle="${esc(t.id)}">${status==='COMPLETE'?'Reopen':'Close task'}</button></td></tr>`;}).join('')||`<tr><td colspan="6" class="empty">No detailed tasks are registered for ${esc(lifecycleTitle(current))}.</td></tr>`;};$('#task-search').addEventListener('input',render);$('#task-filter').addEventListener('change',render);render();
}
function readiness(){
 $('#main').innerHTML=head('Evidence before the next step.','Readiness is a reviewed decision. Open any check to see its meaning, evidence, owner and required action.')+`<div class="callout">Creator outreach waits for social proof and recruitment readiness. Official launch requires all launch checks plus the final team decision.</div><div class="tabs" role="group" aria-label="Readiness category"><button class="selected" data-gate-group="Launch" aria-pressed="true">Official launch</button><button data-gate-group="Social proof" aria-pressed="false">Social proof</button></div><div id="gate-count" class="status-count"></div><div id="gates" class="gate-list"></div>`;
 showGates('Launch');
}
function showGates(group,openId=''){const gates=data.gates.filter(g=>g.group===group);document.querySelectorAll('[data-gate-group]').forEach(b=>{b.classList.toggle('selected',b.dataset.gateGroup===group);b.setAttribute('aria-pressed',String(b.dataset.gateGroup===group));});$('#gate-count').textContent=`${gates.filter(g=>gateStatus(g)==='PASS').length} of ${gates.length} passed · reviewed evidence required`;
 const detail=(name,value)=>value&&value!=='—'?`<div class="gate-detail"><small>${esc(name)}</small><p>${esc(value)}</p></div>`:'';
 $('#gates').innerHTML=gates.map(g=>{const status=gateStatus(g),overridden=Boolean(adminState.gateOverrides[g.id]);return `<details class="gate" data-gate-id="${esc(g.id)}" ${openId===g.id?'open':''}><summary><div class="gate-copy"><small>${esc(g.id)} · ${esc(g.type)}${overridden?' · ADMIN OVERRIDE':''}</small><h3>${esc(g.title)}</h3></div><div class="gate-state">${tag(status)}<span class="gate-chevron" aria-hidden="true">⌄</span></div></summary><div class="gate-details">${detail('Why it matters',g.clarification)}${detail('Related task',g.task)}${detail('Evidence / source',g.source)}${detail('Target',g.target)}${detail('Owner',g.owner)}${detail('Action if not passed',g.action)}${detail('Current source evidence',g.evidence)}<div class="gate-review"><div class="gate-review-head"><div><small>YOUR REVIEW</small><h4>Evidence or decision input</h4></div><span class="save-status" id="gate-save-${esc(g.id)}">Saved on this device</span></div><div class="gate-review-fields"><label>Status<select data-gate-status="${esc(g.id)}">${['WAIT','PASS','FAIL'].map(v=>`<option value="${v}" ${status===v?'selected':''}>${esc(label(v))}</option>`).join('')}</select></label><label class="gate-note-field">Your evidence or clarification<textarea data-gate-note="${esc(g.id)}" rows="4" maxlength="2000" placeholder="What did you review? Add evidence, decision details, links, reviewer and date.">${esc(adminState.gateNotes?.[g.id]||'')}</textarea></label></div><div class="gate-review-actions"><small>PASS or Needs work requires a note. This is an administrative display override; reconcile evidence into the gate register before launch.</small><button class="primary-btn" data-save-gate="${esc(g.id)}">Save review</button></div></div></div></details>`;}).join('');}
function growth(){const b=data.budget;const names=['Total active subscribers','MRR','Activated users','Successful exports'];$('#main').innerHTML=head('Growth that means something.','Subscribers first. Unknown measurements stay unknown.')+`<section class="stats">${names.map(name=>{const m=metric(name);return stat(name,display(m.value),m.value==='UNKNOWN'?'Not yet verified':esc(m.asOf));}).join('')}</section><section class="panel"><div class="panel-head"><h2>Make the $${b.total} count</h2><small>One total project budget</small></div><div class="panel-body budget-layout"><div class="donut" style="--used:${Math.min(100,b.total?b.spent/b.total*100:0)}%"><div class="donut-inner"><strong>${money(b.remaining)}</strong><small>remaining unspent</small></div></div><div class="allocations"><p class="subtle">Planned allocations · each expense needs approval</p>${b.allocations.filter(a=>a.amount>0).map(a=>`<div class="allocation"><span>${esc(a.label)}</span><strong>${money(a.amount)}</strong></div>`).join('')}<p class="subtle section-gap">${money(b.spent)} spent · ${money(b.committed)} committed · ${money(b.proposed)} in expense proposals</p></div></div></section><section class="panel section-gap"><div class="panel-head"><h2>Measurement register</h2><button class="text-btn" data-doc="03_ANALYTICS/METRICS.md">Read evidence ↗</button></div><div class="table-wrap"><table><thead><tr><th>Metric</th><th>Recorded value</th><th>As of / period</th><th>Source</th></tr></thead><tbody>${data.metrics.map(m=>`<tr><td>${esc(m.label)}</td><td>${display(m.value)}</td><td>${m.asOf==='UNKNOWN'?'Not recorded':esc(m.asOf)}</td><td>${esc(m.source)}</td></tr>`).join('')}</tbody></table></div></section><p class="subtle section-gap">A single snapshot cannot establish a trend. Time-series charts can follow when dated observations exist.</p>`;}
function updates(){ $('#main').innerHTML=head('The project’s memory.','Decisions, completed work and changes to the plan.')+`<div class="toolbar"><input id="update-search" type="search" placeholder="Search updates…" aria-label="Search updates"></div><section class="panel"><div class="panel-body" id="timeline"></div></section>`;const render=()=>{const q=$('#update-search').value.toLowerCase();const items=data.updates.filter(u=>`${u.title} ${u.body}`.toLowerCase().includes(q));$('#timeline').innerHTML=items.map((u)=>`<article class="timeline-entry"><time>${esc(u.date||'Date not recorded')}</time><h3>${esc(u.title.replace(/^\d{4}-\d{2}-\d{2}\s*[—–-]?\s*/,''))||'Project update'}</h3><p>${esc(u.body.replace(/[*`#]/g,'').slice(0,230))}${u.body.length>230?'…':''}</p><button class="text-btn section-gap" data-update="${data.updates.indexOf(u)}">Read full update ↗</button></article>`).join('')||'<p class="empty">No matching updates.</p>';};$('#update-search').addEventListener('input',render);render();}
function library(){ $('#main').innerHTML=head('One place for the whole project.','Strategy, research, delivery, content, outreach and operating rules.')+`<div class="toolbar"><input id="doc-search" type="search" placeholder="Search every project document…" aria-label="Search project documents"><select id="doc-area" aria-label="Filter document area"><option value="ALL">All areas</option>${[...new Set(data.docs.map(d=>d.area))].map(a=>`<option>${esc(a)}</option>`).join('')}</select></div><div id="doc-count" class="status-count"></div><div id="docs" class="doc-grid"></div>`;const render=()=>{const q=$('#doc-search').value.toLowerCase(),a=$('#doc-area').value;const docs=data.docs.filter(d=>(a==='ALL'||d.area===a)&&`${d.title} ${d.body}`.toLowerCase().includes(q));$('#doc-count').textContent=`${docs.length} project documents`;$('#docs').innerHTML=docs.map(d=>`<button class="doc-card" data-doc="${esc(d.path)}"><small>${esc(d.area)}</small><h3>${esc(d.title)}</h3><p>Open project record ↗</p></button>`).join('')||'<p class="empty">No matching documents.</p>';};$('#doc-search').addEventListener('input',render);$('#doc-area').addEventListener('change',render);render();}
const sharedDashboardApi='https://reaction-creator-default-rtdb.firebaseio.com/dashboard.json';
const validLifecycles=['PRE_LAUNCH','LAUNCH_READY','LAUNCHED','GROWTH'];
async function patchSharedDashboard(values){const response=await fetch(sharedDashboardApi,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({...values,updatedAt:new Date().toISOString()})});if(!response.ok)throw new Error(`Save failed (${response.status})`);}
async function loadSharedDashboardState(){try{const response=await fetch(`${sharedDashboardApi}?t=${Date.now()}`,{cache:'no-store'});if(!response.ok)throw new Error();const shared=await response.json();if(shared&&typeof shared.overviewNote==='string')adminState.overviewNote=shared.overviewNote;if(validLifecycles.includes(shared?.lifecycle))adminState.project.stage=shared.lifecycle;noteSyncStatus='Shared across devices';await saveAdminState();}catch{noteSyncStatus='Shared dashboard state temporarily unavailable';}}
async function saveSharedOverviewNote(value){await patchSharedDashboard({overviewNote:value});adminState.overviewNote=value;noteSyncStatus='Saved for everyone';await saveAdminState();}
async function saveSharedLifecycle(value){if(!validLifecycles.includes(value))throw new Error('Invalid lifecycle');await patchSharedDashboard({lifecycle:value});adminState.project.stage=value;await saveAdminState();}
function admin(){const p=adminState.project||{};$('#main').innerHTML=head('Project control center.','Lifecycle updates save immediately and apply across the dashboard.',`<span class="tag pass">Shared controls</span>`)+`<div class="admin-grid"><section class="panel"><div class="panel-head"><h2>Project lifecycle</h2><small>Shared across devices</small></div><div class="panel-body form-grid"><label class="full">Lifecycle<select id="project-stage">${validLifecycles.map(v=>`<option value="${v}" ${p.stage===v?'selected':''}>${lifecycleTitle(v)}</option>`).join('')}</select></label><p id="lifecycle-status" class="subtle full">Changing this updates Overview and Plan & tasks immediately.</p></div></section><section class="panel"><div class="panel-head"><h2>Task update</h2><small>Saved on this device</small></div><div class="panel-body form-grid"><label class="full">Task<select id="admin-task">${data.phases.map(p=>`<optgroup label="${esc(p.id)} · ${esc(p.title)}">${data.tasks.filter(t=>t.phaseId===p.id).map(t=>`<option value="${esc(t.id)}">${esc(t.id)} · ${esc(t.title)}</option>`).join('')}</optgroup>`).join('')}</select></label><label>Status<select id="admin-task-status">${['COMPLETE','IN PROGRESS','NOT STARTED','BLOCKED'].map(v=>`<option value="${v}">${label(v)}</option>`).join('')}</select></label><label class="full">Admin note<textarea id="admin-task-note" rows="3" maxlength="1000" placeholder="Decision, blocker, evidence reference or follow-up"></textarea></label><button id="stage-task" class="primary-btn">Save task update</button><p id="admin-save-status" class="subtle full">Task changes stay on this device until reconciled into project records.</p></div></section></div>`;const syncTask=()=>{const id=$('#admin-task').value,t=data.tasks.find(x=>x.id===id);$('#admin-task-status').value=taskStatus(t);$('#admin-task-note').value=adminState.taskNotes?.[id]||'';};$('#admin-task').addEventListener('change',syncTask);$('#project-stage').addEventListener('change',async e=>{const status=$('#lifecycle-status'),value=e.target.value;status.textContent='Saving…';e.target.disabled=true;try{await saveSharedLifecycle(value);status.textContent=`Saved for everyone. Overview and Plan & tasks now show ${lifecycleTitle(value)}.`;}catch(error){status.textContent=error.message;e.target.value=activeLifecycle();}finally{e.target.disabled=false;}});syncTask();}
function navigate(){if(!data)return;view=location.hash.slice(1)||'overview';if(!titles[view])view='overview';$('#crumb').textContent=titles[view];document.querySelectorAll('[data-view]').forEach(a=>{a.classList.toggle('active',a.dataset.view===view);if(a.dataset.view===view)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});({overview,plan,readiness,growth,updates,library,admin}[view])();window.scrollTo(0,0);}
const bytesFromB64=value=>Uint8Array.from(atob(value),c=>c.charCodeAt(0));
const b64FromBytes=value=>btoa(String.fromCharCode(...new Uint8Array(value)));
const localKey='reactioncreator-admin-state-v1';
async function pinKey(pin,salt,iterations=120000){const material=await crypto.subtle.importKey('raw',new TextEncoder().encode(pin),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
async function loadAdminState(){const base=data.adminState||{};adminState={overviewNote:base.overviewNote||'',taskOverrides:{...(base.taskOverrides||{})},taskNotes:{...(base.taskNotes||{})},gateOverrides:{...(base.gateOverrides||{})},gateNotes:{...(base.gateNotes||{})},project:{...(base.project||{})},updates:[...(base.updates||[])]};const saved=localStorage.getItem(localKey);if(!saved)return;try{const payload=JSON.parse(saved),key=await pinKey(activePin,bytesFromB64(payload.salt),payload.iterations),clear=await crypto.subtle.decrypt({name:'AES-GCM',iv:bytesFromB64(payload.iv)},key,bytesFromB64(payload.ciphertext)),local=JSON.parse(new TextDecoder().decode(clear));if(typeof local.overviewNote==='string')adminState.overviewNote=local.overviewNote;if(local.taskOverrides&&typeof local.taskOverrides==='object')Object.assign(adminState.taskOverrides,local.taskOverrides);if(local.taskNotes&&typeof local.taskNotes==='object')Object.assign(adminState.taskNotes,local.taskNotes);if(local.gateOverrides&&typeof local.gateOverrides==='object')Object.assign(adminState.gateOverrides,local.gateOverrides);if(local.gateNotes&&typeof local.gateNotes==='object')Object.assign(adminState.gateNotes,local.gateNotes);if(local.project&&typeof local.project==='object')Object.assign(adminState.project,local.project);if(Array.isArray(local.updates)&&local.updates.length)adminState.updates=local.updates;}catch{localStorage.removeItem(localKey);}}
async function saveAdminState(){const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),iterations=120000,key=await pinKey(activePin,salt,iterations),clear=new TextEncoder().encode(JSON.stringify(adminState)),ciphertext=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,clear);localStorage.setItem(localKey,JSON.stringify({iterations,salt:b64FromBytes(salt),iv:b64FromBytes(iv),ciphertext:b64FromBytes(ciphertext)}));}
async function decryptSnapshot(pin){
 const r=await fetch(`encrypted-data.json?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error('Snapshot unavailable');
 const payload=await r.json();const material=await crypto.subtle.importKey('raw',new TextEncoder().encode(pin),'PBKDF2',false,['deriveKey']);
 const key=await crypto.subtle.deriveKey({name:'PBKDF2',salt:bytesFromB64(payload.salt),iterations:payload.iterations,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['decrypt']);
 const clear=await crypto.subtle.decrypt({name:'AES-GCM',iv:bytesFromB64(payload.iv)},key,bytesFromB64(payload.ciphertext));
 return JSON.parse(new TextDecoder().decode(clear));
}
function reveal(){document.querySelectorAll('.app-shell').forEach(el=>el.hidden=false);$('#lock').hidden=true;navigate();$('#footer').innerHTML=`<span>Project records: ${esc(data.projectDate||'date unknown')} · individual metrics carry their own dates</span><span>Snapshot generated ${esc(new Date(data.generatedAt).toLocaleString())}</span>`;}
async function unlock(pin){const help=$('#pin-help'),button=$('#unlock-form button');button.disabled=true;help.className='pin-help';help.textContent='Unlocking…';try{const next=await decryptSnapshot(pin);if(!Array.isArray(next.tasks)||!next.budget)throw new Error('Invalid snapshot');data=next;activePin=pin;await loadAdminState();await loadSharedDashboardState();failedAttempts=0;reveal();}catch{failedAttempts++;help.className='pin-help error';help.textContent='Incorrect PIN. Try again.';$('#pin').value='';$('#pin').focus();if(failedAttempts>=3)await new Promise(resolve=>setTimeout(resolve,Math.min(5000,failedAttempts*750)));}finally{button.disabled=false;}}
async function load(){const b=$('#refresh');b.disabled=true;b.textContent='Refreshing…';try{const next=await decryptSnapshot(activePin);if(!Array.isArray(next.tasks)||!next.budget)throw new Error('Invalid snapshot');data=next;await loadSharedDashboardState();navigate();$('#footer').innerHTML=`<span>Project records: ${esc(data.projectDate||'date unknown')} · individual metrics carry their own dates</span><span>Snapshot generated ${esc(new Date(data.generatedAt).toLocaleString())}</span>`;}catch{$('#main').innerHTML='<div class="panel empty"><h2>Couldn’t load the project snapshot.</h2><p>Reload the page and unlock it again. No metrics have been substituted.</p></div>';}finally{b.disabled=false;b.textContent='↻ Refresh snapshot';}}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.go)location.hash=b.dataset.go;if(b.dataset.doc)doc(b.dataset.doc);if(b.dataset.task)taskDetail(b.dataset.task);if(b.dataset.taskToggle){const task=data.tasks.find(t=>t.id===b.dataset.taskToggle),current=taskStatus(task);adminState.taskOverrides[task.id]=current==='COMPLETE'?(task.status==='COMPLETE'?'IN PROGRESS':task.status):'COMPLETE';await saveAdminState();plan();}if(b.id==='save-note'||b.id==='clear-note'){const status=$('#note-status'),field=$('#admin-note'),value=b.id==='clear-note'?'':field.value.trim();status.textContent=b.id==='clear-note'?'Clearing…':'Saving…';try{await saveSharedOverviewNote(value);field.value=value;status.textContent=value?'Saved for everyone':'Cleared for everyone';}catch(error){status.textContent=error.message;}}if(b.id==='stage-task'){const id=$('#admin-task').value;adminState.taskOverrides[id]=$('#admin-task-status').value;adminState.taskNotes[id]=$('#admin-task-note').value.trim();await saveAdminState();$('#admin-save-status').textContent=`Saved ${id} on this device.`;}if(b.dataset.saveGate){const id=b.dataset.saveGate,gate=data.gates.find(g=>g.id===id),statusField=document.querySelector(`[data-gate-status="${id}"]`),noteField=document.querySelector(`[data-gate-note="${id}"]`),saveStatus=$(`#gate-save-${id}`),nextStatus=statusField.value,note=noteField.value.trim();if(['PASS','FAIL'].includes(nextStatus)&&!note){saveStatus.textContent='Add an evidence or decision note first.';}else{adminState.gateOverrides[id]=nextStatus;adminState.gateNotes[id]=note;await saveAdminState();showGates(gate.group,id);}}if(b.dataset.gateGroup)showGates(b.dataset.gateGroup);if(b.dataset.phase){const p=data.phases.find(p=>p.id===b.dataset.phase);openDetail(p.id,p.title,tag(p.status)+`<p>${esc(p.outcome)}</p><div class="record-line"><small>Current evidence</small>${esc(p.note)}</div><div class="record-line"><small>Original target</small>${esc(p.target)}</div><p class="subtle">Task dependencies and gate evidence govern advancement.</p>`);}if(b.dataset.update!==undefined){const u=data.updates[Number(b.dataset.update)];openDetail(u.date,u.title,`<pre class="document">${esc(u.body)}</pre>`);}});
$('#unlock-form').addEventListener('submit',e=>{e.preventDefault();const pin=$('#pin').value;if(/^\d{4}$/.test(pin))unlock(pin);});$('#pin').addEventListener('input',e=>{e.target.value=e.target.value.replace(/\D/g,'').slice(0,4);});$('#refresh').addEventListener('click',load);$('#close-detail').addEventListener('click',()=>$('#detail').close());$('#detail').addEventListener('click',e=>{if(e.target===$('#detail')){const r=$('#detail').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('#detail').close();}});window.addEventListener('hashchange',navigate);$('#pin').focus();
